### ISSUE TITLE
emoji&custom emoji

### ISSUE THREAD

**Issue by teacat923** [SamsTheNerd/inline#11]
inline is known to be incompatible with many mods that add emoji, and this is considered to be inline's biggest weakness.

I propose the ability to draw emojis inline.
This is the ideal situation I envision.
1. You can display emojis with [emoji:id]
2. Discord and Twitter emojis can be used by default
3. You can add emoji categories as hover text by hovering over the text.
4. You can add/change emojis through resource packs

**Comment by SamsTheNerd** [comment]
I had plans for a separate mod that would do this, but I've been busy and working on other stuff. 

What are discord/Twitter emojis?

**Comment by teacat923** [comment]
I'm really looking forward to that. Regarding emojis on discord/twitter, I'm talking about the default emojis available. Like this:
![Screenshot_20241208-074753](https://github.com/user-attachments/assets/66e0c015-a197-45f5-bf5c-b23dec4bc7aa)

**Comment by SamsTheNerd** [comment]
Skye made a mod called emojiless that uses inline for emojis, go check it out if you're interested

**Comment by teacat923** [comment]
I searched but couldn't find it. If so, could you please provide a link?

**Comment by SamsTheNerd** [comment]
https://github.com/vgskye/emojiless/releases
modrinth is slow to approve stuff
