### ISSUE TITLE
Startup Crash with Chat Colors

### ISSUE THREAD

**Issue by The-Weeb-Guy** [SamsTheNerd/inline#8]
After hunting through my like 250 mod modpack and adding this to my pack (required dependancy for latest hexcasting build) game started crashing on boot. Iv narrowed the issue down to Inline and Chat Colors and made a fresh instance with just the latest version of 1.20.1 forge, inline, chat colors, and cloth config.
[latest.log](https://github.com/user-attachments/files/17602403/latest.log)
[debug.log](https://github.com/user-attachments/files/17602404/debug.log)
[crash-2024-11-01_13.07.51-client.txt](https://github.com/user-attachments/files/17602407/crash-2024-11-01_13.07.51-client.txt)

**Comment by SamsTheNerd** [comment]
This is likely from the other mod using an unstable mixin technique https://codeberg.org/PORTB/ChatColours/src/commit/e1a5d0601482391632d13d611cefc3758497c5fa/src/main/java/portb/chatcolours/mixin/client/TextProcessingMixin.java#L124 
see [here](https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---Overwriting-Methods) for more info on overwriting methods in mixins and why it requires some care.
I don't believe there's anything I can do about that. I can add an incompatibility note in the readme.
