### ISSUE TITLE
Modern UI incompatibility

### ISSUE THREAD

**Issue by FunnyBunny14** [SamsTheNerd/inline#9]
The mixins for inline break and can't inject when modernui is used. We really quite like it, it's a fast and responsive, and super customisable ui overhaul, but the way inline does stuff doesn't work when it is installed.
Thanks for the caxton compat, by the way! It's a mod that fixes several issues with text and rendering it, and makes the game much, much more playable!

**Comment by SamsTheNerd** [comment]
do you have an error log or a description of what exactly is breaking/steps to reproduce?

**Comment by FunnyBunny14** [comment]
Pretty sure you just install the two alongside eachother, we specifically used neoforge, and the hexcasting build artifacts (but we don't think you'll need it?)
It just doesn't load! And the error was just that the mixin couldn't inject.
We have a bunch of other stuff installed, but uninstalling modernui fixed it, and it worked just fine since (but the modpack is huge, and as a result, so are the logs)

**Comment by SamsTheNerd** [comment]
this looks to be the problem: https://github.com/BloCamLimb/ModernUI-MC/blob/3ae864fc6e765243895d2169620bfeb38ddb1288/common/src/main/java/icyllis/modernui/mc/text/mixin/MixinFontRenderer.java#L113

Overwriting methods in mixins is not good for compatibility, they should look into switching to MixinExtras. There is nothing I can do about it, please open an issue with them. I can update the readme to list it as incompatible until it is fixed on their side.

**Comment by FunnyBunny14** [comment]
Okay, will do! Thank you, and this is now closed then!

**Comment by BloCamLimb** [comment]
Caxton is also not compatible with Inline. It just won't crash the game, but Inline's mixin injectors will not function.

> [BloCamLimb/ModernUI#251](https://github.com/BloCamLimb/ModernUI/issues/251) Workaround to also have modernui: "Open /.minecraft/config/ModernUI/bootstrap.properties, add line modernui_mc_disableTextEngine=true, save as UTF-8 encoding." Then you can install caxton to not have text be illegible and support multiple, proper fonts - with the caveat that it doesn't support iris/oculus shaders for in world text rendering. We suppose this could be added to the readme?
